config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'homes/about'
  devise_for :users
  resources 'reading_books', only: [:show, :create, :destroy, :update]

  get 'books/index'
  resource 'books', only: [:show] do
      resource :book_nices, only: [:create, :destroy]
      resource :book_comments, only: [:create]
  end
  #post 'search' => 'books#search', as: 'search'
  resources 'users', only: [:show, :destroy, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  end

  get 'relationships/follower' => 'relationships#follower', as: 'follower'
  get 'relationships/follow' => 'relationships#follow', as: 'follow'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :user
	belongs_to :follow, class_name: 'User'

	validates :user_id, presence: true
	validates :follow_id, presence: true
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  	before_action :authenticate_user!
	before_action :set_user

	#用途：フォローを作成
	def create
	    user = User.find(params[:follow_id])
	    following = current_user.follow(user)
		redirect_back(fallback_location: root_path)
	end

	#用途：フォローを削除
	def destroy
	    user = User.find(params[:follow_id])
	    following = current_user.unfollow(user)
        redirect_back(fallback_location: root_path)
	end

	#用途：フォロー一覧表示
	def follow
		@user = User.find(params[:follow_id])
		@users = @user.followings
	end

	#用途：フォロワー一覧表示
	def follower
		@user = User.find(params[:follow_id])
		@users = @user.followers
	end


  private

  def set_user
    user = User.find(params[:follow_id])
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_relationships_list.html.erb
<table class="table table-striped">
	<thead>
		<tr>
			<div class="row">
				<div class="col-xs-4">
					<th></th>
				</div>
				<div class="col-xs-4">
					<th>ニックネーム</th>
				</div>
				<div class="col-xs-4">
					<th></th>
				</div>
			</div>
		</tr>
	</thead>
	<tbody>
		<% users.each do |user| %>
			<tr>
				<td>
					<%= attachment_image_tag user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: '50x50' %>
				</td>
				<td>
					<p>
						<%= link_to user_path(user.id) do %>
							<span><%= user.nickname %></span>
						<% end %>
					</p>
				</td>
				<td>
					<% if current_user != user %>
						<% if current_user.following?(user) %>
							<%= link_to 'フォロー外す', user_relationships_path(current_user, follow_id: user.id), method: :delete, class: "btn btn-danger" %>
						<% else %>
							<%= link_to 'フォローする', user_relationships_path(current_user, follow_id: user.id), method: :POST, class: "btn btn-primary" %>
						<% end %>
					<% end %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/relationships/follow.html.erb
<div class="user-follow-form">
	<div class="container">
		<div class="row">
			<div class="col-xs-3">
				<%= render 'users/userinfo', user: @user %>
			</div>

			<div class="col-xs-9 follow-list">
				<h2>フォロー一覧</h2>
				<div class="row">
					<%= render 'relationships/relationships_list', users: @users %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/relationships/follower.html.erb
<div class="user-follower-form">
	<div class="container">
		<div class="row">
			<div class="col-xs-3">
				<%= render 'users/userinfo', user: @user %>
			</div>

			<div class="col-xs-9 follower-list">
				<h2>フォロワー一覧</h2>
				<div class="row">
					<%= render 'relationships/relationships_list', users: @users %>
				</div>
			</div>
		</div>
	</div>
</div>