config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'homes/about'
  devise_for :users
  resources 'reading_books', only: [:show, :create, :destroy, :update]

  get 'books/index'
  resource 'books', only: [:show] do
      resource :book_nices, only: [:create, :destroy]
      resource :book_comments, only: [:create]
  end
  #post 'search' => 'books#search', as: 'search'
  resources 'users', only: [:show, :destroy, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  end

  get 'relationships/follower' => 'relationships#follower', as: 'follower'
  get 'relationships/follow' => 'relationships#follow', as: 'follow'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  #ログイン時に必須のため
  validates :nickname, presence: true

  has_many :readings, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :nices, dependent: :destroy


  # follow用
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :current_user?, except: [:show]

  def show
  	@user = User.find(params[:id])

    @chart = {}
    cnt = 0
    @user.readings.select(:created_at).each do |readed_day|
      cnt += 1
      @chart.store(readed_day.created_at.strftime("%Y-%m-%d"), cnt)
    end
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
  	@user = User.find(current_user.id)

    # パスワードが空ならパスワードは更新しない
    if params[:user][:password].blank?
      params[:user].delete("password")
    end

  	if @user.update(user_permitted_parameters)
  		redirect_to user_path(current_user.id)
  	else
  		render action: :edit
  	end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to root_path
  end



  private
  def user_permitted_parameters
    added_attrs = [ :email, :nickname, :password, :profile_image, :introduction, :spoiler_prevention ]
    params.require(:user).permit(added_attrs)
  end

  def current_user?
    if current_user != User.find(params[:id])
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_userinfo.html.erb
<h2>ユーザー情報</h2>
<div class="user-profile border-inset">
	<div class="row">
		<div class="col-xs-6">
			<%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg", size: '100x100', class: "profile_image" %>
		</div>
		<div class="col-xs-6 user-nickname">
			<h3><%= user.nickname %></h3>
		</div>
	</div>


	<% if current_user != user %>
	  <% if current_user.following?(user) %>
	    <%= link_to 'フォロー外す', user_relationships_path(current_user, follow_id: user.id), method: :delete, class: "btn btn-danger" %>
	  <% else %>
	    <%= link_to 'フォローする', user_relationships_path(current_user, follow_id: user.id), method: :POST, class: "btn btn-primary" %>
	  <% end %>
    <% else %>
		<%= link_to 'プロフィール編集', edit_user_path(current_user), class:"btn btn-warning" %>
	<% end %>



	<h4>リンク</h4>
	<table class="table table-striped">
	  <tbody>
	      <tr>
	          <td><%= link_to '本棚', reading_book_path(@user.id), class:"header-menu-item"  %></td>
	      </tr>
	      <tr>
	          <td><%= link_to 'フォロー数：' + user.followings.count.to_s, follow_path(follow_id: user.id) %></td>
		  </tr>
	      <tr>
	          <td><%= link_to 'フォロワー数：' + user.followers.count.to_s, follower_path(follow_id: user.id) %></td>
		  </tr>
<!-- 	      <tr>
	          <td><a href="" class="comment">コメント</a></td>
	      </tr> -->
	  </tbody>
	</table>

	<h4>自己紹介</h4>
	<span><%= user.introduction %></span>

</div>




app/views/users/edit.html.erb
<div class="user-edit-form">
  <div class="input-user-info">
    <div class="container">
      <div class="input-user-info-title">
        <div class="row">
          <div class="col-xs-12">
            <h2>プロフィール編集</h2>
          </div>
        </div>
      </div>

      <%= form_for(@user, url: user_path(@user.id)) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        <div class="input-user-info-body">

          <div class="row">
            <div class="field">
              <div class="col-xs-4">
                <p><span>ニックネーム</span></p>
              </div>
              <div class="col-xs-8">
                <%= f.text_field :nickname, autofocus: true, autocomplete: "nickname", class: "nickname" %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="field">
              <%= f.attachment_field :profile_image, class: "profile_image" %>
            </div>
          </div>

          <div class="row">
            <div class="field">
              <div class="col-xs-4">
                <p><span>自己紹介</span></p>
              </div>
              <div class="col-xs-8">
                <%= f.text_area :introduction, autofocus: true, autocomplete: "introduction", class: "introduction" %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="field">
              <div class="col-xs-4">
                <p><span>メールアドレス</span></p>
              </div>
              <div class="col-xs-8">
                <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"user-email" %>
              </div>
            </div>
          </div>

          <div class="row">
            <div class="field">
              <div class="col-xs-4">
                <p><span>パスワード</span></p>
              </div>
              <div class="col-xs-8">
                <%= f.password_field :password, autocomplete: "new-password", class:"new-password" %>
              </div>
            </div>
          </div>

          <em>(6文字以上入力してください)</em>
          <p>※パスワードを変更した場合、トップ画面へ戻ります。</p>

          <div class="row">
            <div class="field">
              <div class="col-xs-4">
                <span>ネタばれ防止機能</span>
              </div>
              <div class="col-xs-8">
                <%= f.check_box :spoiler_prevention, class:"spoiler_prevention" %>
              </div>
            </div>
          </div>



<!--           <div class="row">
            <div class="field">
              <div class="col-xs-4">
                <p><span>現在のパスワード</span></p>
              </div>
              <div class="col-xs-8">
                <%= f.password_field :current_password, autocomplete: "current-password" %>
              </div>
            </div>
          </div>

          <% if @minimum_password_length %>
            <em>(<%= @minimum_password_length %> 文字以上入力してください)</em>
          <% end %>
 -->
          <div class="button-field">
            <div class="row">
              <div class="field">
                <div class="col-xs-6">
                  <div class="button-update">
                    <%= f.submit "更新", class:"btn btn-warning btn-lg" %>
                  </div>
                </div>
                <div class="col-xs-6">
                  <div class="button-back">
                    <%= link_to "戻る", :back, class:"btn btn-info btn-lg"  %>
                  </div>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="field">
                <div class="col-xs-12">
                  <br/>
                  <div class="button-delete">
                    <%= link_to '退会する', user_path(@user), method: :delete, data: { confirm: '退会しますか？' }, class:"btn btn-danger btn-lg" %>
                  </div>
                </div>
              </div>
            </div>
          </div>

        </div>
      <% end %>
    </div>
  </div>
</div>


app/views/users/show.html.erb
<div class="user-show-form">
	<div class="container">
		<div class="row">
			<div class="col-xs-3">
				<%= render 'users/userinfo', user: @user %>
			</div>

			<div class="col-xs-9">
				<h2>読書グラフ</h2>
				<div class="border-solid">
					<%#= line_chart @chart, width: "800px", height: "400px", class: "reading_chart" %>
					<%= line_chart @chart %>
				</div>
			</div>
		</div>
	</div>
</div>