config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'homes/about'
  devise_for :users
  resources 'reading_books', only: [:show, :create, :destroy, :update]

  get 'books/index'
  resource 'books', only: [:show] do
      resource :book_nices, only: [:create, :destroy]
      resource :book_comments, only: [:create]
  end
  #post 'search' => 'books#search', as: 'search'
  resources 'users', only: [:show, :destroy, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  end

  get 'relationships/follower' => 'relationships#follower', as: 'follower'
  get 'relationships/follow' => 'relationships#follow', as: 'follow'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
	validates :selflink, presence: true

	has_many :readings, dependent: :destroy
	has_many :comments, dependent: :destroy
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	def show
		@response = get_json_from_selflink(params[:search])
		@search = params[:search]

		# isbnで検索した結果が空の場合.newで宣言
		if @response["totalItems"] == 0
			@reading = Reading.new
		else
			# google book apiからjsonファイルを取得できているのでbookテーブルに登録
			# まだ登録されていないisbnなら登録
			@book = create	# createを実施

			if user_signed_in?
				# 読書履歴情報取得
				# ユーザーの読書履歴にあるか確認
				if Reading.find_by(user_id: current_user.id, book_id: @book.id).nil?
					@reading = Reading.new
				else
					@reading = Reading.find_by(user_id: current_user.id, book_id: @book.id)
				end
			end

			# コメント情報取得
			comments = @book.comments.order(created_at: "DESC")
			@comments = comments.page(params[:page])
		end
	end

	def index
	 	if params[:search].blank?
	 		# 空白なら画面は元の画面のまま
	 		redirect_back(fallback_location: root_path)
	 	else
			@response = get_json_from_q(params[:search])
			#@response = @response.page(params[:page])
			@search = params[:search]
	 	end
	end

	private

	# 検索に成功した書籍情報の登録
	# Bookに未登録ならSAVE。登録済みなら登録情報を返す
	def create
		if Book.find_by(selflink: @response["selfLink"])
			book = Book.find_by(selflink: @response["selfLink"])
		else
			book = Book.new(selflink: @response["selfLink"])
			book.save
		end

		return book
	end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book_status.html.erb
<!-- 読書ステータスを非同期で更新 -->
<div class="book-status-form">
	<h4 class="font-bold">本の登録</h4>

	<div id="book-status">
      	<% if reading[:id].nil? %>
		    <%= link_to '読了に登録', reading_books_path(reading_status: 4, book_id: book_id), method: :post, remote: true, class: "btn btn-default book-status-item" %>
      	<% else %>
      		<% if reading[:readed_status] %>
      			<!-- 読了の場合 -->
				<p class="btn btn-warning book-status-item">読了</p>
      		<% else %>
      			<!-- 未読了の場合 -->
			    <%= link_to '読了に登録', reading_book_path(reading[:id], reading_status: 4, book_id: book_id), method: :put, remote: true, class: "btn btn-default book-status-item" %>
      		<% end %>
      	<% end %>


      	<% if reading[:id].nil? %>
		    <%= link_to '読んでいる本に登録', reading_books_path(reading_status: 3, book_id: book_id), method: :post, remote: true, class: "btn btn-default book-status-item" %>
      	<% else %>
      		<% if reading[:reading_status] == 3 %>
      			<!-- 読了の場合 -->
      			<% if reading[:readed_status] %>
				    <%= link_to '読んでいる本から解除', reading_book_path(reading[:id], reading_status: 0, book_id: book_id), method: :put, remote: true, class: "btn btn-warning book-status-item" %>
				<% else %>
					<%= link_to '読んでいる本から解除', reading_book_path(reading[:id], reading_status: 3, book_id: book_id), method: :delete, remote: true, class: "btn btn-warning book-status-item" %>

				<% end %>
      		<% else %>
      			<!-- 未読了の場合 -->
			    <%= link_to '読んでいる本に登録', reading_book_path(reading[:id], reading_status: 3, book_id: book_id), method: :put, remote: true, class: "btn btn-default book-status-item" %>
      		<% end %>
      	<% end %>

		<% if reading[:id].nil? %>
			<%= link_to '積読本に登録', reading_books_path(reading_status: 2, book_id: book_id), method: :post, remote: true, class: "btn btn-default book-status-item" %>
		<% else %>
			<% if reading[:reading_status] == 2 %>
				<!-- 読了の場合 -->
				<% if reading[:readed_status] %>
				    <%= link_to '積読本から解除', reading_book_path(reading[:id], reading_status: 0, book_id: book_id), method: :put, remote: true, class: "btn btn-warning book-status-item" %>
				<% else %>
					<%= link_to '積読本から解除', reading_book_path(reading[:id], reading_status: 2, book_id: book_id), method: :delete, remote: true, class: "btn btn-warning book-status-item" %>
				<% end %>
			<% else %>
				<!-- 未読了の場合 -->
			    <%= link_to '積読本に登録', reading_book_path(reading[:id], reading_status: 2, book_id: book_id), method: :put, remote: true, class: "btn btn-default book-status-item" %>
			<% end %>
		<% end %>

		<% if reading[:id].nil? %>
			<%= link_to '読みたい本に登録', reading_books_path(reading_status: 1, book_id: book_id), method: :post, remote: true, class: "btn btn-default book-status-item" %>
		<% else %>
			<% if reading[:reading_status] == 1 %>
				<!-- 読了の場合 -->
				<% if reading[:readed_status] %>
				    <%= link_to '読みたい本から解除', reading_book_path(reading[:id], reading_status: 0, book_id: book_id), method: :put, remote: true, class: "btn btn-warning book-status-item" %>
				<% else %>
					<%= link_to '読みたい本から解除', reading_book_path(reading[:id], reading_status: 1, book_id: book_id), method: :delete, remote: true, class: "btn btn-warning book-status-item" %>
				<% end %>
			<% else %>
				<!-- 未読了の場合 -->
		    	<%= link_to '読みたい本に登録', reading_book_path(reading[:id], reading_status: 1, book_id: book_id), method: :put, remote: true, class: "btn btn-default book-status-item" %>
			<% end %>
		<% end %>
	</div>
</div>

app/views/books/index.html.erb
<div class="book-index-form">
	<div class="container">
		<% if @response["totalItems"] == 0 %>
			<h2 class="font-bold">検索条件「<%= @search %>」に関連する書籍はありませんでした</h2>
		<% else %>
			<div>
				<h2 class="font-bold">検索条件「<%= @search %>」に関連する書籍を最大40件表示します</h2>
			</div>

			<div class="row">
				<div class="book-index">
					<% @response["items"].each do |response| %>

						<div class="col-xs-2">
							<div class="book-index-item-image">
								<%#= link_to books_path(search: response["volumeInfo"]["industryIdentifiers"][1]["identifier"]) do %>
								<%= link_to books_path(search: response["selfLink"]) do %>
									<% unless response["volumeInfo"]["imageLinks"].blank? %>
										<%= image_tag response["volumeInfo"]["imageLinks"]["smallThumbnail"], :size =>'128x182', class: "book_image" %>
									<% else %>
										<%= image_tag 'no_book_image.jpg', :size => '128x128', class: "no_book_image" %>
									<% end %>
								<% end %>
							</div>
						</div>
					<% end %>
				</div>
			</div>
		<% end %>
	</div>
</div>

<footer></footer>

app/views/books/show.html.erb
<div class="book-show-form">
	<div class="container">
		<div class="row">
			<div class="col-xs-12">
				<h2 class="font-bold"><%= @response["volumeInfo"]["title"] %></h2>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-3 border-inset book-sidebar-block">
				<div class="book-sidebar">
					<% unless @response["volumeInfo"]["imageLinks"].blank? %>
						<%= image_tag @response["volumeInfo"]["imageLinks"]["smallThumbnail"], class: "book_image" %><br/>
					<% else %>
						<img src="assets/no_book_image.jpg" width="60" height="60" title="no_image">
					<% end %>

					<h4 class="font-bold">作者</h4>
					<% unless @response["volumeInfo"]["authors"].blank? %>
						<p>
							<% @response["volumeInfo"]["authors"].each do |author| %>
									<%= author %><br/>
							<% end %>
						</p>
					<% else %>
						<p>不明</p>
					<% end %>

					<% if user_signed_in? %>
						<%= render 'books/book_status', reading: @reading, book_id: @book.id %>
					<% end %>

					<h4 class="font-bold">概要</h4>
					<p>
						<%= @response["volumeInfo"]["description"] %>
					</p>
				</div>
			</div>

			<div class="col-xs-9 book-comment-block">
				<% if user_signed_in? %>
					<%= render 'book_comments/book_comment', book: @book, comments: @comments %>
				<% end %>
			</div>
		</div>
	</div>
</div>