config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'homes/about'
  devise_for :users
  resources 'reading_books', only: [:show, :create, :destroy, :update]

  get 'books/index'
  resource 'books', only: [:show] do
      resource :book_nices, only: [:create, :destroy]
      resource :book_comments, only: [:create]
  end
  #post 'search' => 'books#search', as: 'search'
  resources 'users', only: [:show, :destroy, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  end

  get 'relationships/follower' => 'relationships#follower', as: 'follower'
  get 'relationships/follow' => 'relationships#follow', as: 'follow'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :selflink, presence: true

	has_many :readings, dependent: :destroy
	has_many :comments, dependent: :destroy
end

app/models/child_comment.rb
class ChildComment < ApplicationRecord
	belongs_to :comment
	validates :comment_id, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :book
	has_many :child_comments
	has_many :nices

	validates :user_id, presence: true
	validates :book_id, presence: true
	validates :comment, presence: true

	paginates_per 5

	def niced_by?(user)
    	self.nices.where(user_id: user.id).exists?
  	end
end

app/models/follow.rb
class Follow < ApplicationRecord
	belongs_to :user

	validates :user_id, presence: true
	validates :follow_id, presence: true
end

app/models/nice.rb
class Nice < ApplicationRecord
	belongs_to :user
	belongs_to :comment

	validates :user_id, presence: true
	validates :comment_id, presence: true
end

app/models/reading.rb
class Reading < ApplicationRecord
	belongs_to :user
	belongs_to :book

	validates :user_id, presence: true
	validates :book_id, presence: true
    validates :reading_status, presence: true
    validates :readed_status, inclusion: {in: [true, false]}
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :user
	belongs_to :follow, class_name: 'User'

	validates :user_id, presence: true
	validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  #ログイン時に必須のため
  validates :nickname, presence: true

  has_many :readings, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :nices, dependent: :destroy


  # follow用
  has_many :relationships, dependent: :destroy
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  MAX_RESULT = 40  # 仕様上限の40件を表示
  API_URL = 'https://www.googleapis.com/books/v1/volumes?'  # 検索URL
  ORDER_BY = 'relevance'  # 関連度順

  # Devise::Controllers::Helpersのメソッドをオーバーライド
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  #sign_out後のredirect先変更する。rootパスへ。rootパスはhome topを設定済み。
  def after_sign_out_path_for(resource)
    root_path
  end

  # ISBNによる検索
  def get_json_from_q(target)
    client = HTTPClient.new

    #request =  client.get('https://www.googleapis.com/books/v1/volumes?q=isbn:' + isbn)
    request =  client.get(URI.encode(API_URL + 'q=' + target + '&orderBy=' + ORDER_BY + '&maxResults=' + MAX_RESULT.to_s))
    response = JSON.parse(request.body)
    return response
  end

  def get_json_from_selflink(link)
    client = HTTPClient.new

    request =  client.get(link)
    response = JSON.parse(request.body)
    return response
  end

  # View側からでも使用できるようにする
  helper_method :get_json_from_selflink

  protected
  def configure_permitted_parameters
    added_attrs = [ :email, :nickname, :password, :spoiler_prevention ]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end
end

app/controllers/book_nices_controller.rb
class BookNicesController < ApplicationController
  # BooksNicesだがbookのコメントに対していいねを行う
  before_action :authenticate_user!
  def create
  	@cmt = Comment.find_by(id: params[:comment_id])
    @book = Book.find_by(id: @cmt.book_id)
  	nice = current_user.nices.new(comment_id: @cmt.id)
  	nice.save
  end

  def destroy
  	@cmt = Comment.find_by(id: params[:comment_id])
    @book = Book.find_by(id: @cmt.book_id)
  	nice = current_user.nices.find_by(comment_id: @cmt.id)
  	nice.destroy
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	def show
		@response = get_json_from_selflink(params[:search])
		@search = params[:search]

		# isbnで検索した結果が空の場合.newで宣言
		if @response["totalItems"] == 0
			@reading = Reading.new
		else
			# google book apiからjsonファイルを取得できているのでbookテーブルに登録
			# まだ登録されていないisbnなら登録
			@book = create	# createを実施

			if user_signed_in?
				# 読書履歴情報取得
				# ユーザーの読書履歴にあるか確認
				if Reading.find_by(user_id: current_user.id, book_id: @book.id).nil?
					@reading = Reading.new
				else
					@reading = Reading.find_by(user_id: current_user.id, book_id: @book.id)
				end
			end

			# コメント情報取得
			comments = @book.comments.order(created_at: "DESC")
			@comments = comments.page(params[:page])
		end
	end

	def index
	 	if params[:search].blank?
	 		# 空白なら画面は元の画面のまま
	 		redirect_back(fallback_location: root_path)
	 	else
			@response = get_json_from_q(params[:search])
			#@response = @response.page(params[:page])
			@search = params[:search]
	 	end
	end

	private

	# 検索に成功した書籍情報の登録
	# Bookに未登録ならSAVE。登録済みなら登録情報を返す
	def create
		if Book.find_by(selflink: @response["selfLink"])
			book = Book.find_by(selflink: @response["selfLink"])
		else
			book = Book.new(selflink: @response["selfLink"])
			book.save
		end

		return book
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  	# コメント数の多い上3つを取得
  	rank_book = Book.find(Comment.group(:book_id).order('count(book_id) desc').limit(3).pluck(:book_id))

	@ranking = []
	@book_id = []
  	rank_book.each do |rank|
  		@ranking.push(get_json_from_selflink(rank.selflink))
  		@book_id.push(rank.id)
  	end
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :current_user?, except: [:show]

  def show
  	@user = User.find(params[:id])

    @chart = {}
    cnt = 0
    @user.readings.select(:created_at).each do |readed_day|
      cnt += 1
      @chart.store(readed_day.created_at.strftime("%Y-%m-%d"), cnt)
    end
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
  	@user = User.find(current_user.id)

    # パスワードが空ならパスワードは更新しない
    if params[:user][:password].blank?
      params[:user].delete("password")
    end

  	if @user.update(user_permitted_parameters)
  		redirect_to user_path(current_user.id)
  	else
  		render action: :edit
  	end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to root_path
  end



  private
  def user_permitted_parameters
    added_attrs = [ :email, :nickname, :password, :profile_image, :introduction, :spoiler_prevention ]
    params.require(:user).permit(added_attrs)
  end

  def current_user?
    if current_user != User.find(params[:id])
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/reading_books_helper.rb
module ReadingBooksHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
    <div class = "alert alert-warning">
        <ul>
        	<h2><%= model.errors.count %> errors prohibited this obj from being saved:</h2>
            <% model.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NoBookNoLife</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
      <nav class="navbar navbar-default header-navbar">
        <div class="container">
          <div class="row">
            <div class="col-xs-12">
              <h1><%= link_to 'NoBookNoLife', root_path, class:"header-menu-logo" %></h1>
            </div>
          </div>
          <div class="row">
            <div>
              <ul class="nav navbar-nav navbar-right header-menu">
                <% if user_signed_in? %>
                  <div class="col-xs-4">
                    <li>
                      <span><%= link_to 'マイページ', user_path(current_user.id), class:"header-menu-item"  %></span>
                    </li>
                  </div>
                  <div class="col-xs-2">
                    <li>
                      <span><%= link_to '本棚', reading_book_path(current_user.id), class:"header-menu-item"  %></span>
                    </li>
                  </div>
                  <div class="col-xs-4">
                    <li>
                      <span><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:"header-menu-item"  %></span>
                    </li>
                  </div>
                <% else %>
                  <div class="col-xs-4">
                    <li>
                      <span><%= link_to 'このサイトについて', homes_about_path, class:"header-menu-item"  %></span>
                    </li>
                  </div>
                  <div class="col-xs-4">
                    <li>
                      <span><%= link_to '新規登録', new_user_registration_path, class:"header-menu-item"  %></span>
                    </li>
                  </div>
                  <div class="col-xs-4">
                    <li>
                      <span><%= link_to 'ログイン', user_session_path, class:"header-menu-item"  %></span>
                    </li>
                  </div>
                <% end %>
              </ul>
            </div>
          </div>

          <div class="row">
            <div class="col-xs-11">
              <div class="search-bar navbar-text navbar-right">
                <%= form_with url: books_index_path, local: true, method: :get do |f| %>
                  <%= f.text_field :search, placeholder: "タイトル、作者名を入力してください", class: "search_text" %>
                  <%= f.submit "検索", class: "search_button" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </nav>
    </div>
    <%= yield %>
  </body>
</html>